image: gradle:jdk17

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "9477386"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget unzip
  - wget https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip -O cmd.zip
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - unzip cmd.zip -d $ANDROID_HOME/cmdline-tools
  - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/tools
  - yes | $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager --licenses
  - $ANDROID_HOME/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-$ANDROID_COMPILE_SDK" "build-tools;$ANDROID_BUILD_TOOLS"
  - chmod +x ./gradlew


build_debug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
  only:
    - merge_requests

build_release:
  stage: build
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/app-release.apk
    expire_in: 1 week
  only:
    - merge_requests

run_tests:
  stage: test
  script:
    - ./gradlew test
  only:
    - merge_requests
